   
name: ci and cd
on:
  push:
    branches:
      - "master"

env:
  AWS_REGION: "ap-south-1"
  CLUSTER_NAME: "demo-cluster"
  SERVICE_NAME: "web-service"
      
jobs:
  build:
    name: Clone, Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cncf-indore:build-${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/cncf-indore:latest

  deploy:
    name: Deploy to ECS
    needs: build
    runs-on: ubuntu-latest

    steps:
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update ECS Service
      run: |
          aws ecs update-service --cluster ${{ env.CLUSTER_NAME }} --service ${{ env.SERVICE_NAME }} --force-new-deployment
      
  

       
  